# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1


# Define a job to be invoked later in a workflow.
jobs:
  artifact-build:
    macos:
      xcode: "13.4"
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Install CMake"
          command: "brew install cmake"
      - run:
          name: "Configure Barrel build"
          command: "mkdir build && cd $_ && cmake .."
      - run:
          name: "Build Barrel"
          command: "cd build && cmake --build . --target install"
      - run:
          name: "Export short SHA"
          command: echo 'export _SHA=`git rev-parse --short HEAD`' >> $BASH_ENV
      - run:
          name: "Package Barrel"
          command: "mv install barrel-$CIRCLE_BRANCH-$_SHA && zip -r barrel-$CIRCLE_BRANCH-$_SHA barrel-$CIRCLE_BRANCH-$_SHA"
      - run:
          name: "Store artifacts"
          command: "mkdir /tmp/download && cp barrel-$CIRCLE_BRANCH-$_SHA.zip /tmp/download"
      - store_artifacts:
          path: /tmp/download
          destination: CircleCI
  static-analysis:
    macos:
      xcode: "13.4"
    resource_class: medium
    steps:
      - checkout
      - run:
          name: "Install Cppcheck"
          command: "brew install cppcheck"
      - run:
          name: "Run Cppcheck"
          command: "cppcheck --output-file=static-analysis-report.txt --quiet --enable=style --enable=information --language=c++ --std=c++20 --platform=unix64 --max-ctu-depth=5 --suppress=missingIncludeSystem --suppress=AssignmentIntegerToAddress include/*"
      - store_artifacts:
          path: static-analysis-report.txt
      - run:
          name: "Validate static analysis"
          command: "[ -s static-analysis-report.txt ] && exit 1 || exit 0"


# Invoke jobs via workflows
workflows:
  build:
    jobs:
      - artifact-build:
          filters:
            branches:
              only:
                - master
      - static-analysis:
          requires:
            - artifact-build
          filters:
            branches:
              only:
                - master
